name: Build Workflow

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        # - windows-latest # disabled because we don't support windows
        ocaml-compiler:
          - 4.12.x
        # - 4.13.x # disabled because we don't support 4.13.x 
        refresh_packages:
          - vendored_packages
          - nightly_packages
        build_cache:
          - use_build_cache
          - no_build_cache

    runs-on: ${{ matrix.os }}

    steps:
      - name: Correct OpenSSL Version on OSX
        if: runner.os == 'macOS'
        run: brew install openssl@3

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache things
        uses: actions/cache@v2
        with:
          path: |
            _opam 
            _build
          key: ${{ runner.os }}-${{ matrix.refresh_packages}}

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Pull Nightly Packages
        if: matrix.refresh_packages == 'nightly_packages'
        run: ./import-scripts/all.sh

      - name: Prepare
        run: ./scripts/prepare_ci.sh

      - name: Clean Build
        if: matrix.build_cache == 'no_build_cache'
        run: opam exec -- dune clean

      - name: Build My Things
        run: opam exec -- dune build --display short @lib/all

      - name: Build Everything
        run: opam exec -- dune build --display short 
