name: Build Workflow

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        # - windows-latest # disabled because we don't support windows
        ocaml-compiler:
          - 4.12.x
        # - 4.13.x # disabled because we don't support 4.13.x 

    runs-on: ${{ matrix.os }}

    steps:
      - name: Correct OpenSSL Version on OSX
        if: runner.os == 'macOS'
        run: brew install openssl@3

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
            #          opam-repositories: |
            #default: https://github.com/ocaml/opam-repository.git
            #janestreet-bleeding: https://ocaml.janestreet.com/opam-repository
            #janestreet-bleeding-external: https://github.com/janestreet/opam-repository.git#external-packages
      - run: ./scripts/prepare.sh
        #- run: opam exec -- dune build
        #- run: opam exec -- dune runtest
